version: '3.5'
services:

  jmeter-server-01:
    image: apache-jmeter
    container_name: jmeter-server-01
    environment:
      - JMETER_OUTPUT_PATH=/tmp/jmeter
      - JMETER_SERVER_ENABLED=TRUE
    ports:
      - 1099:1099
      - 60002:60000
    volumes:
      - /tmp/jmeter/jmeter-server01:/tmp/jmeter
    labels:
      label.jmeter-server: jmeter-server-01
    networks:
      - jmeter-network
      
  jmeter-server-02:
    image: apache-jmeter
    container_name: jmeter-server-02
    environment:
      - JMETER_OUTPUT_PATH=/tmp/jmeter
      - JMETER_SERVER_ENABLED=TRUE
    ports:
      - 1098:1099
      - 60001:60000
    volumes:
      - /tmp/jmeter/jmeter-server02:/tmp/jmeter
    labels:
      label.jmeter-server: jmeter-server-02
    networks:
      - jmeter-network

  jmeter-server-03:
    image: apache-jmeter
    container_name: jmeter-server-03
    environment:
      - JMETER_OUTPUT_PATH=/tmp/jmeter
      - JMETER_SERVER_ENABLED=TRUE
    ports:
      - 1097:1099
      - 60000:60000
    volumes:
      - /tmp/jmeter/jmeter-server03:/tmp/jmeter
    labels:
      label.jmeter-server: jmeter-server-03
    networks:
      - jmeter-network

networks:
  jmeter-network:
    name: jmeter-network