version: '3'
services:

  jmeter-server-01:
    image: apache-jmeter
    container_name: jmeter-server-01
    environment:
      - JMETER_OUTPUT_PATH=/tmp/jmeter
      - JMETER_SERVER_ENABLED=TRUE
    ports:
      - 1099:1099
    volumes:
      - /tmp/tempdir/jmeter-server01:/tmp/jmeter
    labels:
      label.jmeter-server: jmeter-server-01

  jmeter-server-02:
    image: apache-jmeter
    container_name: jmeter-server-02
    environment:
      - JMETER_OUTPUT_PATH=/tmp/jmeter
      - JMETER_SERVER_ENABLED=TRUE
    ports:
      - 1098:1099
    volumes:
      - /tmp/tempdir/jmeter-server02:/tmp/jmeter
    labels:
      label.jmeter-server: jmeter-server-02

  jmeter-server-03:
    image: apache-jmeter
    container_name: jmeter-server-03
    environment:
      - JMETER_OUTPUT_PATH=/tmp/jmeter
      - JMETER_SERVER_ENABLED=TRUE
    ports:
      - 1097:1099
    volumes:
      - /tmp/tempdir/jmeter-server03:/tmp/jmeter
    labels:
      label.jmeter-server: jmeter-server-03

  minio-server:
    image: minio/minio
    container_name: minio-server
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE 
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - 9000:9000
    volumes:
      - /tmp/minio-server/minio-data:/storage
      - /tmp/minio-server/minio-config:/root/.minio
    command:
      - 'server'
      - '/data'
    labels:
      label.jmeter-server: minio-server